import type { Metadata } from "next";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using OctoBoost.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <Navbar />

      <div className="mx-auto max-w-2xl px-6 pt-24 pb-16">
        <h1 className="mb-8 text-3xl font-bold">Terms of Service</h1>
        <div className="prose prose-invert prose-sm max-w-none text-muted">
          <p>Last updated: February 21, 2026</p>

          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using OctoBoost (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

          <h2>2. Description of Service</h2>
          <p>OctoBoost is an automated SEO content platform that analyzes websites, generates articles, and publishes them across third-party platforms. The Service is provided &quot;as is&quot; and may change over time.</p>

          <h2>3. User Accounts</h2>
          <p>You are responsible for maintaining the security of your account credentials. You must not share your account with others or use the Service for any unlawful purpose.</p>

          <h2>4. Content & Publishing</h2>
          <p>Articles generated by OctoBoost are created using AI. You are responsible for reviewing content before publishing. OctoBoost is not liable for content published to third-party platforms through your account.</p>

          <h2>5. API Keys & Third-Party Services</h2>
          <p>You may provide API keys to connect third-party platforms (Dev.to, Hashnode, WordPress, etc.). OctoBoost stores these keys securely and uses them solely to publish content on your behalf. You are responsible for complying with each platform&apos;s terms of service.</p>

          <h2>6. Limitation of Liability</h2>
          <p>OctoBoost is provided without warranties of any kind. We are not responsible for any damages resulting from the use of the Service, including but not limited to loss of data, traffic, or revenue.</p>

          <h2>7. Changes to Terms</h2>
          <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>

          <h2>8. Contact</h2>
          <p>For questions about these Terms, contact us at support@octoboost.app.</p>
        </div>
      </div>
      <Footer />
    </main>
  );
}
